@startuml
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI #FFFFFF
    Class WhereGotTime #BBBBBB
    Class DeleteCommand #FFFFFF
    Class Timetable #FFFFFF
}

Class "<$user>" as User

User <.down.> UI

UI -right-> WhereGotTime
WhereGotTime -down-> DeleteCommand
Timetable <-> DeleteCommand
DeleteCommand -> UI

@enduml
