@startuml
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI #FFFFFF
    Class WhereGotTime #BBBBBB
    Class FindCommand #FFFFFF
    Class Timetable #FFFFFF
}

Class "<$user>" as User

User <.down.> UI

UI -right-> WhereGotTime
WhereGotTime -down-> FindCommand
Timetable -> FindCommand
FindCommand -> UI

@enduml
